# Разрешаем локальные подключения внутри контейнера
local   all             all                                     trust
host    all             all             127.0.0.1/32            trust
host    all             all             ::1/128                 trust

# Разрешаем сетевые подключения к базам данных по паролю
host    all             all             all                     scram-sha-256

# РАЗРЕШАЕМ РЕПЛИКАЦИЮ ДЛЯ ВСЕХ КОНТЕЙНЕРОВ В СЕТИ DOCKER (без шифрования)
host    replication     all             all                     trust
